Repository johnwmillr/LyricsGenius, pull requests merged in 2018-02, with the labels that each got.

#16 fixed TypeError
  genius/api.py
Labels: bug

#17 Moving to python module
  .gitignore
  .travis.yml
  README.md
  credentials.ini.enc
  genius/__init__.py
  genius/api.py
  setup.py
  tests/test_genius.py
Labels: enhancement

#19 Include search for alternate artist names
  genius/api.py
Labels: bug

#20 Add lyrics export from Artist class to .txt or .json formats
  .gitignore
  lyricsgenius/artist.py
  lyricsgenius/song.py
  setup.py
  tests/test_genius.py
Labels: enhancement

#25 Fix Unicode bugs (remove Python 2 support)
  .travis.yml
  lyricsgenius/api.py
  lyricsgenius/artist.py
  lyricsgenius/song.py
  setup.py
  tests/test_genius.py
Labels: bug, enhancement
